server:
  port: 8082
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: testDB
    url: jdbc:mysql://localhost:3306/product_service
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true